services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password 
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
