version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: goalzi_db
      POSTGRES_USER: goalzi_user
      POSTGRES_PASSWORD: goalzi_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: